// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import { group, sleep, check } from "k6";

export let options = {
  scenarios: {
    smoke_test: {
      executor: "constant-vus",
      vus: 5,
      duration: "20s",
    },
    load_test: {
      executor: "constant-vus",
      vus: 30,
      duration: "40s",
      startTime: "25s",
    },
  },
  maxRedirects: 4,
  thresholds: {
    http_req_duration: ["p(95)<1000"],
    http_req_failed: ["rate<0.01"],
    checks: ["rate>0.99"],
  },
};

const Request = Symbol.for("request");

postman[Symbol.for("initial")]( {
  options,
  environment: {
    BaseURL: "https://dummyjson.com",
    userId: "6",
    cartId: "",
  },
});

export default function () {
  group("Cart Copy", function () {

    // -------------------------
    //  Get all carts
    // -------------------------
    postman[Request]( {
      name: "Get all carts",
      id: "ff37f601-93ff-40fd-a19a-cc2d8c0b885e",
      method: "GET",
      address: "{{BaseURL}}/carts",
      post(response) {

        const responseBody = pm.response.json();

        
        pm.test("Status code is 200", () => {
          pm.expect(pm.response.code).to.eql(200);
        });

        pm.test("Response time is acceptable", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });

        pm.test("Response is JSON", () => {
          pm.response.to.be.json;
        });

        pm.test("Carts array exists", () => {
          pm.expect(responseBody.carts).to.be.an("array");
        });

        // k6 performance checks
        check(response, {
          "Get all carts - status is 200": (r) => r.status === 200,
          "Get all carts - response time < 2s": (r) =>
            r.timings.duration < 2000,
        });

        const carts = responseBody.carts;
        const randomIndex = Math.floor(Math.random() * carts.length);
        const randomCart = carts[randomIndex];
        pm.environment.set("cartId", randomCart.id);
      },
    });

    sleep(1);

    // -------------------------
    //  Get single cart
    // -------------------------
    postman[Request]( {
      name: "Get a single cart",
      id: "ce14c855-2d1b-40e8-8f2b-4bdcd0850b37",
      method: "GET",
      address: "{{BaseURL}}/carts/{{cartId}}",
      post(response) {

        const responseBody = pm.response.json();

        pm.test("Status code is 200 OK", () => {
          pm.expect(pm.response.code).to.eql(200);
        });

        pm.test("Response is valid JSON", () => {
          pm.response.to.be.json;
        });

        // k6 checks
        check(response, {
          "Get single cart - status is 200": (r) => r.status === 200,
          "Get single cart - response time < 2s": (r) =>
            r.timings.duration < 2000,
        });
      },
    });

    sleep(1);

    // -------------------------
    // Get carts by user
    // -------------------------
    postman[Request]( {
      name: "Get carts by a user",
      id: "e458cf98-c44d-4bab-82b8-163b2c521964",
      method: "GET",
      address: "{{BaseURL}}/carts/user/{{userId}}",
      post(response) {

        const responseBody = pm.response.json();

        pm.test("Status code is 200", () => {
          pm.expect(pm.response.code).to.eql(200);
        });

        pm.test("Response is JSON", () => {
          pm.response.to.be.json;
        });

        // k6 checks
        check(response, {
          "Get carts by user - status is 200": (r) => r.status === 200,
          "Get carts by user - response time < 2s": (r) =>
            r.timings.duration < 2000,
        });
      },
    });

  });

  sleep(1);

  
}

